sudo: required

services:
  - docker

script:
  - |
    set -e
    for path in `find . -name Dockerfile`; do
        echo $path
        docker run --rm -i pdericson/hadolint < $path
    done
  - |
    set -e
    if [ "$TRAVIS_BRANCH" = master -a "$TRAVIS_PULL_REQUEST" = false ]; then
        for path in `find . -name Dockerfile`; do
            echo $path
            docker run --rm -i mesoscloud/centos:`basename $(dirname $path)` yum check-update
        done
    done
